export const VALIDATION_ADD = "VALIDATION_ADD";
export const VALIDATION_ADD_ALL = "VALIDATION_ADD_ALL";
export const VALIDATION_REMOVE = "VALIDATION_REMOVE";

export const MESSAGE_ADD = "MESSAGE_ADD";
export const MESSAGE_ADD_ALL = "MESSAGE_ADD_ALL";
export const MESSAGE_REMOVE = "MESSAGE_REMOVE";


export const SWITCH_LANGUAGE = "SWITCH_LANGUAGE";

export const VERIFICATION = "VERIFICATION";
