/*
 * Globalize Culture en-US
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function (window, undefined) {

	var Globalize = window.Globalize;

	Globalize.cultures["en-US"] = $.extend(true, Globalize.cultures["en-US"], {
		messages: {
			common: {
				ok: "Ok",
				error: "Error",
				loading: "Loading..."
			},
			geo: {
				unavailable: "Geolocation not supported",
				error: {
					1: "Permission denied",
					2: "Position unavailable",
					3: "Request timeout"
				}
			}
		}
	});

}(this));
